app = "muezzin-reminder-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
source="myapp_data"
destination="/data"

[[services]]
  internal_port = 8080
  protocol = "tcp"
    [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true
    
    [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"